type Mayonnaise = {
  name: string;
  ingredient: string;
  portion: string;
  image: string;
};

const rawMayonaisse: Mayonnaise[] = [
  {
    name: "pumpkin",
    ingredient: "mashed pumpkin",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise01",
  },
  {
    name: "radish",
    ingredient: "grated radish",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise02",
  },
  {
    name: "green onion",
    ingredient: "minced green onion",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise03",
  },
  {
    name: "avocado",
    ingredient: "mashed avocado",
    portion: "3 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise04",
  },
  {
    name: "parsley",
    ingredient: "minced parsley",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise05",
  },
  {
    name: "onion",
    ingredient: "minced onion",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise06",
  },
  {
    name: "edamame",
    ingredient: "cooked & mashed edamame",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise07",
  },
  {
    name: "chickpeas",
    ingredient: "cooked & mashed chickpeas",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise08",
  },
  {
    name: "corn",
    ingredient: "pureed corn",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise09",
  },
  {
    name: "dill",
    ingredient: "minced dill",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise10",
  },
  {
    name: "cilantro",
    ingredient: "minced cilantro",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise11",
  },
  {
    name: "lemon",
    ingredient: "lemon juice",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise12",
  },
  {
    name: "lime",
    ingredient: "lime juice & zest",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise13",
  },
  {
    name: "orange",
    ingredient: "orange juice ] zest",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise14",
  },
  {
    name: "pineapple",
    ingredient: "minced pineapple",
    portion: "1.5 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise15",
  },
  {
    name: "mixed berries",
    ingredient: "defrosted & mashed berries",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise16",
  },
  {
    name: "tofu",
    ingredient: "mashed silk tofu",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise17",
  },
  {
    name: "liver pâté",
    ingredient: "liver pâté",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise18",
  },
  {
    name: "whipped cream",
    ingredient: "whipped cream",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise19",
  },
  {
    name: "condensed milk",
    ingredient: "condensed milk",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise20",
  },
  {
    name: "sake",
    ingredient: "sake (sweet)",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise21",
  },
  {
    name: "sea salt",
    ingredient: "sea salt",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise22",
  },
  {
    name: "bouillon",
    ingredient: "vegetable bouillon",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise23",
  },
  {
    name: "balsamic vinegar",
    ingredient: "vbalsamic vinegar",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise24",
  },
  {
    name: "tahini sauce",
    ingredient: "tahini sauce",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise25",
  },
  {
    name: "caesar sauce",
    ingredient: "caesar sauce",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise26",
  },
  {
    name: "Italian dressing",
    ingredient: "Italian dressing",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise27",
  },
  {
    name: "cream cheese",
    ingredient: "cream cheese",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise28",
  },
  {
    name: "parmesan cheese",
    ingredient: "parmesan cheese",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise29",
  },
  {
    name: "blue cheese",
    ingredient: "blue cheese",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise30",
  },
  {
    name: "coconut milk",
    ingredient: "coconut milk",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise31",
  },
  {
    name: "salsa",
    ingredient: "Italian dressing",
    portion: "1.5 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise32",
  },
  {
    name: "yogurt",
    ingredient: "plain yogurt",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise33",
  },
  {
    name: "butter",
    ingredient: "melted butter",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise34",
  },
  {
    name: "olive oil",
    ingredient: "olive oil",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise35",
  },
  {
    name: "sesame oil",
    ingredient: "sesame oil",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise36",
  },
  {
    name: "soy sauce",
    ingredient: "soy sauce",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise37",
  },
  {
    name: "fish sauce",
    ingredient: "fish sauce",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise38",
  },
  {
    name: "ponzu sauce",
    ingredient: "ponzu sauce",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise39",
  },
  {
    name: "worcester sauce",
    ingredient: "worcester sauce",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise40",
  },
  {
    name: "ketchup",
    ingredient: "ketchup",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise41",
  },
  {
    name: "oyster sauce",
    ingredient: "oyster sauce",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise42",
  },
  {
    name: "sweet chili sauce",
    ingredient: "sweet chili sauce",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise43",
  },
  {
    name: "",
    ingredient: "pesto sauce",
    portion: "0.5 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise44",
  },
  {
    name: "anchovy",
    ingredient: "minced anchovy",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise45",
  },
  {
    name: "BBQ sauce",
    ingredient: "BBQ sauce",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise46",
  },
  {
    name: "chili oil",
    ingredient: "chili oil",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise47",
  },
  {
    name: "chili flakes",
    ingredient: "chili flakes",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise48",
  },
  {
    name: "Sriracha sauce",
    ingredient: "Sriracha sauce",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise49",
  },
  {
    name: "black bean paste",
    ingredient: "black bean paste",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise50",
  },
  {
    name: "miso paste",
    ingredient: "miso paste",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise51",
  },
  {
    name: "Hacho miso paste",
    ingredient: "Hacho miso paste",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise52",
  },
  {
    name: "black pepper",
    ingredient: "black pepper",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise53",
  },
  {
    name: "spice mix",
    ingredient: "spice mix",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise54",
  },
  {
    name: "Japanese pepper",
    ingredient: "Japanese pepper",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise55",
  },
  {
    name: "wasabi",
    ingredient: "wasabi",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise56",
  },
  {
    name: "horseradish",
    ingredient: "horse radish",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise57",
  },
  {
    name: "garlic",
    ingredient: "grated garlic",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise58",
  },
  {
    name: "yuzu kosho",
    ingredient: "yuzu kosho",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise59",
  },
  {
    name: "curry mix",
    ingredient: "curry mix",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise60",
  },
  {
    name: "mustard",
    ingredient: "mustard",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise61",
  },
  {
    name: "paprika",
    ingredient: "paprika",
    portion: "0.25 tsp.",
    image: "/assets/mayo-image/image_mayonnaise62",
  },
  {
    name: "oregano",
    ingredient: "oregano",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise63",
  },
  {
    name: "black sesame",
    ingredient: "ground black sesame",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise64",
  },
  {
    name: "white sesame",
    ingredient: "ground white sesame",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise65",
  },
  {
    name: "seaweed",
    ingredient: "seaweed flakes",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise66",
  },
  {
    name: "shiso",
    ingredient: "shiso flakes",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise67",
  },
  {
    name: "matcha green tea",
    ingredient: "matcha green tea powder with water",
    portion: "1.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise68",
  },
  {
    name: "honey",
    ingredient: "honey",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise69",
  },
  {
    name: "maple syrup",
    ingredient: "maple syrup",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise70",
  },
  {
    name: "sweet bean paste",
    ingredient: "sweet bean paste",
    portion: "1.5 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise71",
  },
  {
    name: "raisin",
    ingredient: "minced raisin",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise72",
  },
  {
    name: "dried apricot",
    ingredient: "dried apricot",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise73",
  },
  {
    name: "dried mango",
    ingredient: "dried mango",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise74",
  },
  {
    name: "strawberry jam",
    ingredient: "strawberry jam",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise75",
  },
  {
    name: "marmalade",
    ingredient: "marmalade",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise76",
  },
  {
    name: "blueberry jam",
    ingredient: "blueberry jam",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise77",
  },
  {
    name: "peach",
    ingredient: "minced canned peach",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise78",
  },
  {
    name: "pickled plum",
    ingredient: "pickled plum",
    portion: "0.5 tsp.",
    image: "/assets/mayo-image/image_mayonnaise79",
  },
  {
    name: "code roe",
    ingredient: "code roe",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise80",
  },
  {
    name: "spiced code roe",
    ingredient: "spiced code roe",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise81",
  },
  {
    name: "date",
    ingredient: "minced dried dates",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise82",
  },
  {
    name: "mushroom",
    ingredient: "minced canned mushroom",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise83",
  },
  {
    name: "bonito",
    ingredient: "bonito flakes",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise84",
  },
  {
    name: "shrimp",
    ingredient: "minced dried shrimp",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise85",
  },
  {
    name: "minced sea kelp",
    ingredient: "sea kelp flakes",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise86",
  },
  {
    name: "surimi",
    ingredient: "minced surimi",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise87",
  },
  {
    name: "salmon",
    ingredient: "minced salmon",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise88",
  },
  {
    name: "tuna",
    ingredient: "canned tuna",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise89",
  },
  {
    name: "mackerel",
    ingredient: "canned mackerel",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise90",
  },
  {
    name: "corned beef",
    ingredient: "corned beef",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise91",
  },
  {
    name: "pickle",
    ingredient: "minced pickle",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise92",
  },
  {
    name: "plum",
    ingredient: "minced plum",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise93",
  },
  {
    name: "sauerkraut",
    ingredient: "minced sauerkraut",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise94",
  },
  {
    name: "kimchi",
    ingredient: "kimchi",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise95",
  },
  {
    name: "bamboo shoot",
    ingredient: "minced bamboo shoots",
    portion: "2 tsp.",
    image: "/assets/mayo-image/image_mayonnaise96",
  },
  {
    name: "dried tomato",
    ingredient: "minced dried tomato",
    portion: "1 tsp.",
    image: "/assets/mayo-image/image_mayonnaise97",
  },
  {
    name: "fried onion",
    ingredient: "fried onion",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise98",
  },
  {
    name: "boiled egg",
    ingredient: "boiled egg",
    portion: "1 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise99",
  },
  {
    name: "potato chips",
    ingredient: "crushed potato chips",
    portion: "2 tbsp.",
    image: "/assets/mayo-image/image_mayonnaise100",
  },
];
